export const DEFAULT_WORKZONE_TYPES = [
  {
    name: "Personal Finance",
    icon: 1,
    //color: '#F7E1EE',
    color: "1",
    description: "Manage your personal income, bills, and day-to-day expenses.",
    default_categories: [
      // ---- incomes ----
      { name: "Salary / Wages", type: "income", icon_id: "25" },
      { name: "Bonuses / Overtime", type: "income", icon_id: "2" },
      { name: "Interest Income", type: "income", icon_id: "4" },
      { name: "Dividends", type: "income", icon_id: "7" },
      {
        name: "Rental Income (occasional personal)",
        type: "income",
        icon_id: "22",
      },
      { name: "Side Hustle / Freelance Income", type: "income", icon_id: "2" },
      { name: "Government Payments", type: "income", icon_id: "13" },
      { name: "Gifts Received", type: "income", icon_id: "12" },
      { name: "Refunds & Rebates", type: "income", icon_id: "6" },
      { name: "Insurance Payouts", type: "income", icon_id: "10" },
      { name: "Other Income", type: "income", icon_id: "19" },
      { name: "Opening Balance", type: "income", icon_id: "18" },

      // ---- expenses ----
      { name: "Rent / Mortgage Payments", type: "expense", icon_id: "67" },
      { name: "Electricity & Gas", type: "expense", icon_id: "47" },
      { name: "Water & Sewer", type: "expense", icon_id: "47" },
      { name: "Internet / Phone / Mobile", type: "expense", icon_id: "61" },
      { name: "Rates & Taxes (non-business)", type: "expense", icon_id: "76" },
      { name: "Home Maintenance & Repairs", type: "expense", icon_id: "34" },
      { name: "Fuel / Petrol", type: "expense", icon_id: "21" },
      { name: "Public Transport", type: "expense", icon_id: "77" },
      { name: "Parking & Tolls", type: "expense", icon_id: "71" },
      { name: "Vehicle Maintenance & Repairs", type: "expense", icon_id: "91" },
      { name: "Vehicle Insurance", type: "expense", icon_id: "26" },
      { name: "Registration / Licensing", type: "expense", icon_id: "63" },
      { name: "Groceries", type: "expense", icon_id: "28" },
      { name: "Household Supplies", type: "expense", icon_id: "29" },
      { name: "Personal Care Products", type: "expense", icon_id: "88" },
      { name: "Restaurants / Cafés", type: "expense", icon_id: "46" },
      { name: "Takeaway / Delivery", type: "expense", icon_id: "46" },
      { name: "Movies / Events / Shows", type: "expense", icon_id: "9" },
      { name: "Subscriptions", type: "expense", icon_id: "34" },
      { name: "Health Insurance", type: "expense", icon_id: "60" },
      { name: "Medical & Dental", type: "expense", icon_id: "60" },
      { name: "Fitness / Gym Membership", type: "expense", icon_id: "50" },
      { name: "Pharmacy / Medicines", type: "expense", icon_id: "58" },
      { name: "Tuition / Course Fees", type: "expense", icon_id: "44" },
      { name: "Books & Materials", type: "expense", icon_id: "6" },
      { name: "School Fees", type: "expense", icon_id: "44" },
      { name: "Clothing & Footwear", type: "expense", icon_id: "40" },
      { name: "Accessories & Bags", type: "expense", icon_id: "43" },
      { name: "Haircuts & Grooming", type: "expense", icon_id: "57" },
      { name: "Bank Fees", type: "expense", icon_id: "45" },
      { name: "Loan Repayments (Personal)", type: "expense", icon_id: "16" },
      { name: "Loan Repayments (Business)", type: "expense", icon_id: "16" },
      {
        name: "Credit Card Payments (non-business)",
        type: "expense",
        icon_id: "16",
      },
      { name: "Life / Personal Insurance", type: "expense", icon_id: "58" },
      { name: "Gifts Purchased", type: "expense", icon_id: "12" },
      { name: "Charitable Donations", type: "expense", icon_id: "36" },
      { name: "Flights", type: "expense", icon_id: "51" },
      { name: "Accommodation", type: "expense", icon_id: "52" },
      { name: "Travel Insurance", type: "expense", icon_id: "60" },
      { name: "Tours & Activities", type: "expense", icon_id: "89" },
      { name: "Pet Expenses", type: "expense", icon_id: "73" },
      { name: "Hobbies & Leisure", type: "expense", icon_id: "37" },
      { name: "Other Uncategorised Spending", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Business Operations",
    icon: 2,
    //color: '#DED1F5',
    color: "2",
    description: "Track company expenses and operational costs.",
    default_categories: [
      // ---- incomes ----
      { name: "Sales – Products", type: "income", icon_id: "17" },
      { name: "Sales – Services", type: "income", icon_id: "17" },
      { name: "Project Income", type: "income", icon_id: "3" },
      {
        name: "Rental Income (Business Assets)",
        type: "income",
        icon_id: "22",
      },
      { name: "Commission Income", type: "income", icon_id: "4" },
      { name: "Consulting Fees", type: "income", icon_id: "5" },
      { name: "Government Grants / Rebates", type: "income", icon_id: "13" },
      { name: "Interest Income", type: "income", icon_id: "8" },
      { name: "Royalties & Licensing", type: "income", icon_id: "24" },
      { name: "Stock Income", type: "income", icon_id: "7" },
      { name: "Other Business Income", type: "income", icon_id: "19" },

      // ---- expenses ----
      { name: "Office Rent / Lease", type: "expense", icon_id: "67" },
      { name: "Utilities", type: "expense", icon_id: "90" },
      { name: "Internet / Phone", type: "expense", icon_id: "15" },
      { name: "Office Supplies & Stationery", type: "expense", icon_id: "68" },
      { name: "Software Subscriptions", type: "expense", icon_id: "83" },
      { name: "Printing & Postage", type: "expense", icon_id: "68" },
      { name: "Fuel", type: "expense", icon_id: "54" },
      { name: "Vehicle Maintenance & Repairs", type: "expense", icon_id: "20" },
      { name: "Registration & Licensing", type: "expense", icon_id: "21" },
      { name: "Vehicle Insurance", type: "expense", icon_id: "91" },
      { name: "Parking & Tolls", type: "expense", icon_id: "23" },
      { name: "Freight & Courier", type: "expense", icon_id: "25" },
      { name: "Salaries & Wages", type: "expense", icon_id: "26" },
      { name: "Superannuation Contributions", type: "expense", icon_id: "72" },
      { name: "Contractor Payments", type: "expense", icon_id: "28" },
      { name: "Staff Training & Development", type: "expense", icon_id: "85" },
      { name: "Staff Amenities", type: "expense", icon_id: "85" },
      { name: "Recruitment Costs", type: "expense", icon_id: "78" },
      { name: "Advertising", type: "expense", icon_id: "1" },
      { name: "Social Media Ads", type: "expense", icon_id: "1" },
      { name: "Promotional Materials", type: "expense", icon_id: "32" },
      { name: "Sponsorships & Events", type: "expense", icon_id: "9" },
      { name: "Client Entertainment", type: "expense", icon_id: "39" },
      { name: "Raw Materials", type: "expense", icon_id: "64" },
      { name: "Inventory Purchases", type: "expense", icon_id: "20" },
      { name: "Equipment Hire", type: "expense", icon_id: "49" },
      { name: "Packaging & Labels", type: "expense", icon_id: "70" },
      { name: "Outsourced Services", type: "expense", icon_id: "69" },
      {
        name: "Accounting & Book keeping Fees",
        type: "expense",
        icon_id: "31",
      },
      { name: "Legal Fees", type: "expense", icon_id: "62" },
      { name: "Bank Fees", type: "expense", icon_id: "44" },
      { name: "Loan Repayments (Business)", type: "expense", icon_id: "6" },
      { name: "Business Insurance", type: "expense", icon_id: "60" },
      { name: "Flights", type: "expense", icon_id: "47" },
      { name: "Hotels / Accommodation", type: "expense", icon_id: "89" },
      {
        name: "Meals & Entertainment (Business Travel)",
        type: "expense",
        icon_id: "46",
      },
      { name: "Conferences & Seminars", type: "expense", icon_id: "41" },
      { name: "Equipment Repairs", type: "expense", icon_id: "51" },
      { name: "Building Maintenance", type: "expense", icon_id: "21" },
      { name: "Licences & Permits", type: "expense", icon_id: "63" },
      { name: "Memberships & Subscriptions", type: "expense", icon_id: "66" },
      { name: "Other Business Expenses", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Team Collaboration",
    icon: 3,
    //color: '#FFE1D9',
    color: "3",
    description: "Plan and track expenses for teams and group activities.",
    default_categories: [
      // ---- incomes ----
      { name: "Team Project Income", type: "income", icon_id: "29" },
      { name: "Client Payments", type: "income", icon_id: "0" },
      { name: "Sponsorship Contributions", type: "income", icon_id: "28" },
      { name: "Membership Fees", type: "income", icon_id: "29" },
      { name: "Grant / Funding Income", type: "income", icon_id: "13" },
      { name: "Reimbursements from Members", type: "income", icon_id: "23" },
      { name: "Event Ticket Sales", type: "income", icon_id: "21" },
      { name: "Merchandise Sales", type: "income", icon_id: "17" },
      { name: "Other Team Income", type: "income", icon_id: "29" },

      // ---- expenses ----
      { name: "Venue Hire / Office Space", type: "expense", icon_id: "10" },
      { name: "Utilities (shared office)", type: "expense", icon_id: "90" },
      { name: "Internet & Phone", type: "expense", icon_id: "15" },
      { name: "Office Supplies", type: "expense", icon_id: "16" },
      { name: "Software / Team Tools", type: "expense", icon_id: "83" },
      { name: "Printing & Postage", type: "expense", icon_id: "69" },
      { name: "Fuel / Transport Costs", type: "expense", icon_id: "54" },
      { name: "Vehicle Hire", type: "expense", icon_id: "35" },
      { name: "Flights", type: "expense", icon_id: "21" },
      { name: "Accommodation (Team Trips)", type: "expense", icon_id: "89" },
      {
        name: "Meals & Catering (Team Events)",
        type: "expense",
        icon_id: "23",
      },
      { name: "Parking & Tolls", type: "expense", icon_id: "25" },
      { name: "Advertising & Promotion", type: "expense", icon_id: "32" },
      { name: "Event Setup & Decoration", type: "expense", icon_id: "84" },
      { name: "Promotional Materials", type: "expense", icon_id: "28" },
      { name: "Sponsorship Costs", type: "expense", icon_id: "84" },
      { name: "Photography / Videography", type: "expense", icon_id: "0" },
      { name: "Contractor / Freelancer Fees", type: "expense", icon_id: "5" },
      { name: "Training & Development", type: "expense", icon_id: "30" },
      { name: "Uniforms / Team Apparel", type: "expense", icon_id: "40" },
      { name: "Volunteer Allowances", type: "expense", icon_id: "2" },
      { name: "Materials & Supplies", type: "expense", icon_id: "64" },
      { name: "Equipment Hire / Purchase", type: "expense", icon_id: "49" },
      { name: "Outsourced Services", type: "expense", icon_id: "37" },
      { name: "Technology & Devices", type: "expense", icon_id: "83" },
      { name: "Accounting / Bookkeeping", type: "expense", icon_id: "31" },
      { name: "Bank Fees", type: "expense", icon_id: "40" },
      { name: "Insurance (Team or Event)", type: "expense", icon_id: "60" },
      { name: "Licences & Permits", type: "expense", icon_id: "42" },
      { name: "Gifts & Thank-You Items", type: "expense", icon_id: "56" },
      { name: "Contingency Costs", type: "expense", icon_id: "84" },
      { name: "Other Team Expenses", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Project Management",
    icon: 4,
    // color: '#FFDFAC',
    color: "4",
    description:
      "Track costs and tasks for individual or multi-phase projects.",
    default_categories: [
      // ---- incomes ----
      { name: "Project Payments (Client)", type: "income", icon_id: "3" },
      { name: "Milestone Payments", type: "income", icon_id: "3" },
      { name: "Progress Payments", type: "income", icon_id: "3" },
      {
        name: "Change Order / Variation Income",
        type: "income",
        icon_id: "19",
      },
      {
        name: "Government Grants / Project Funding",
        type: "income",
        icon_id: "13",
      },
      { name: "Reimbursements from Clients", type: "income", icon_id: "23" },
      { name: "Equipment Hire Income", type: "income", icon_id: "49" },
      { name: "Consulting Fees (Project)", type: "income", icon_id: "5" },
      { name: "Other Project Income", type: "income", icon_id: "19" },

      // ---- expenses ----
      { name: "Materials & Supplies", type: "expense", icon_id: "13" },
      { name: "Subcontractor Payments", type: "expense", icon_id: "3" },
      { name: "Equipment Hire / Lease", type: "expense", icon_id: "49" },
      { name: "Software & Project Tools", type: "expense", icon_id: "83" },
      { name: "Packaging & Shipping", type: "expense", icon_id: "70" },
      { name: "Employee Wages (Project)", type: "expense", icon_id: "25" },
      { name: "Contractor / Consultant Fees", type: "expense", icon_id: "5" },
      { name: "Training & Skills Development", type: "expense", icon_id: "30" },
      { name: "Travel Allowances", type: "expense", icon_id: "2" },
      { name: "Fuel & Vehicle Use", type: "expense", icon_id: "54" },
      { name: "Flights", type: "expense", icon_id: "23" },
      { name: "Accommodation", type: "expense", icon_id: "25" },
      { name: "Meals & Catering (On-Site)", type: "expense", icon_id: "46" },
      { name: "Parking & Tolls", type: "expense", icon_id: "27" },
      { name: "Meetings & Presentation Costs", type: "expense", icon_id: "65" },
      { name: "Client Entertainment", type: "expense", icon_id: "29" },
      {
        name: "Promotional / Launch Materials",
        type: "expense",
        icon_id: "32",
      },
      { name: "Office / Site Utilities", type: "expense", icon_id: "90" },
      { name: "Printing & Documentation", type: "expense", icon_id: "68" },
      { name: "Licences & Permits", type: "expense", icon_id: "33" },
      { name: "Insurance (Project Specific)", type: "expense", icon_id: "60" },
      { name: "Equipment Repairs", type: "expense", icon_id: "35" },
      { name: "Site Maintenance", type: "expense", icon_id: "21" },
      { name: "Accounting / Bookkeeping Fees", type: "expense", icon_id: "37" },
      { name: "Bank Fees", type: "expense", icon_id: "38" },
      { name: "Legal Fees", type: "expense", icon_id: "62" },
      {
        name: "Gifts / Tokens of Appreciation",
        type: "expense",
        icon_id: "13",
      },
      { name: "Contingency & Unplanned Costs", type: "expense", icon_id: "84" },
      { name: "Other Project Expenses", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Vehicle Expenses",
    icon: 5,
    // color: '#FFF3CB',
    color: "5",
    description:
      "Maintain all expenses related to vehicle ownership or fleets.",
    default_categories: [
      // ---- incomes ----
      { name: "Vehicle Hire / Rental Income", type: "income", icon_id: "29" },
      { name: "Delivery / Transport Income", type: "income", icon_id: "77" },
      {
        name: "Reimbursements (Fuel / Mileage)",
        type: "income",
        icon_id: "23",
      },
      { name: "Insurance Payouts (Vehicle)", type: "income", icon_id: "14" },
      { name: "Sale of Vehicle or Parts", type: "income", icon_id: "35" },
      { name: "Other Vehicle-Related Income", type: "income", icon_id: "19" },

      // ---- expenses ----
      { name: "Fuel / Petrol / Diesel", type: "expense", icon_id: "54" },
      { name: "EV Charging", type: "expense", icon_id: "53" },
      { name: "Oil & Lubricants", type: "expense", icon_id: "15" },
      { name: "Routine Servicing", type: "expense", icon_id: "27" },
      { name: "Mechanical Repairs", type: "expense", icon_id: "27" },
      { name: "Tyres & Wheel Alignment", type: "expense", icon_id: "27" },
      { name: "Battery Replacement", type: "expense", icon_id: "19" },
      { name: "Car Wash & Detailing", type: "expense", icon_id: "20" },
      { name: "Vehicle Insurance", type: "expense", icon_id: "21" },
      { name: "Extended Warranty", type: "expense", icon_id: "91" },
      { name: "Roadside Assistance", type: "expense", icon_id: "80" },
      { name: "Registration Fees", type: "expense", icon_id: "44" },
      { name: "Road Tolls & E-Tags", type: "expense", icon_id: "70" },
      { name: "Safety Inspections", type: "expense", icon_id: "82" },
      { name: "Licences & Permits", type: "expense", icon_id: "28" },
      { name: "Parking Fees", type: "expense", icon_id: "71" },
      {
        name: "Rental / Lease Payments (Vehicle)",
        type: "expense",
        icon_id: "22",
      },
      { name: "Hire of Additional Vehicles", type: "expense", icon_id: "35" },
      { name: "Accessories & Modifications", type: "expense", icon_id: "59" },
      { name: "Other Vehicle Expenses", type: "expense", icon_id: "33" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Investment Property",
    icon: 6,
    // color: '#FFF3CB',
    color: "6",
    description:
      "Track income and expenses related to rental or investment properties.",
    default_categories: [
      // ---- incomes ----
      { name: "Rental Income", type: "income", icon_id: "22" },
      { name: "Bond Refunds", type: "income", icon_id: "4" },
      { name: "Back Rent / Arrears Received", type: "income", icon_id: "22" },
      { name: "Tenant Reimbursements", type: "income", icon_id: "23" },
      { name: "Insurance Payouts (Property)", type: "income", icon_id: "14" },
      {
        name: "Government Rebates / Incentives",
        type: "income",
        icon_id: "13",
      },
      { name: "Sale Proceeds (Property)", type: "income", icon_id: "19" },
      { name: "Other Property Income", type: "income", icon_id: "19" },

      // ---- expenses ----
      { name: "Property Management Fees", type: "expense", icon_id: "76" },
      { name: "Letting / Leasing Fees", type: "expense", icon_id: "31" },
      { name: "Advertising for Tenants", type: "expense", icon_id: "32" },
      { name: "Legal Fees (Tenancy)", type: "expense", icon_id: "62" },
      { name: "General Repairs", type: "expense", icon_id: "27" },
      { name: "Emergency Repairs", type: "expense", icon_id: "27" },
      { name: "Cleaning & Pest Control", type: "expense", icon_id: "38" },
      { name: "Gardening / Landscaping", type: "expense", icon_id: "21" },
      { name: "Pool Maintenance", type: "expense", icon_id: "21" },
      { name: "Equipment Repairs ", type: "expense", icon_id: "27" },
      { name: "Council Rates", type: "expense", icon_id: "76" },
      { name: "Water Rates", type: "expense", icon_id: "76" },
      { name: "Land Tax", type: "expense", icon_id: "76" },
      { name: "Strata / Body Corporate Fees", type: "expense", icon_id: "31" },
      {
        name: "Electricity / Gas (if paid by owner)",
        type: "expense",
        icon_id: "47",
      },
      {
        name: "Loan Interest (Investment Loan)",
        type: "expense",
        icon_id: "16",
      },
      { name: "Bank Fees", type: "expense", icon_id: "29" },
      { name: "Mortgage Insurance", type: "expense", icon_id: "60" },
      { name: "Landlord Insurance", type: "expense", icon_id: "60" },
      { name: "Building Insurance", type: "expense", icon_id: "60" },
      {
        name: "Contents Insurance (if furnished)",
        type: "expense",
        icon_id: "60",
      },
      {
        name: "Fuel & Parking (for inspections)",
        type: "expense",
        icon_id: "71",
      },
      { name: "Public Transport to Property", type: "expense", icon_id: "77" },
      {
        name: "Security (Locks, Alarms, Cameras)",
        type: "expense",
        icon_id: "81",
      },
      {
        name: "Depreciable Assets (Appliances, Furniture)",
        type: "expense",
        icon_id: "45",
      },
      { name: "Other Property Expenses", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Travel & Events",
    icon: 7,
    // color: '#FFFCA7'
    color: "7",
    description: "Organize travel and event-related costs.",
    default_categories: [
      // ---- incomes ----
      { name: "Ticket Sales", type: "income", icon_id: "84" },
      { name: "Sponsorship Income", type: "income", icon_id: "28" },
      { name: "Event Registration Fees", type: "income", icon_id: "84" },
      { name: "Merchandise Sales", type: "income", icon_id: "26" },
      { name: "Vendor / Stall Fees", type: "income", icon_id: "33" },
      {
        name: "Grants / Funding (Event or Trip)",
        type: "income",
        icon_id: "26",
      },
      { name: "Refunds / Cancellations", type: "income", icon_id: "20" },
      {
        name: "Reimbursements (Travel or Event)",
        type: "income",
        icon_id: "23",
      },
      { name: "Other Travel/Event Income", type: "income", icon_id: "0" }, //two categories

      // ---- expenses ----
      { name: "Flights / Airfare", type: "expense", icon_id: "51" },
      { name: "Train / Bus / Ferry Fares", type: "expense", icon_id: "77" },
      { name: "Car Hire & Fuel", type: "expense", icon_id: "54" },
      { name: "Taxis & Ride-Sharing", type: "expense", icon_id: "77" },
      { name: "Travel Insurance", type: "expense", icon_id: "89" },
      { name: "Hotels / Motels", type: "expense", icon_id: "89" },
      { name: "Airbnb / Short-Stay Rentals", type: "expense", icon_id: "89" },
      { name: "Camping / Caravan Parks", type: "expense", icon_id: "71" },
      { name: "Restaurants & Cafés", type: "expense", icon_id: "46" },
      { name: "Catering Services", type: "expense", icon_id: "89" },
      { name: "Beverages & Snacks", type: "expense", icon_id: "52" },
      { name: "Venue Hire", type: "expense", icon_id: "11" },
      { name: "Decoration & Setup", type: "expense", icon_id: "84" },
      { name: "Entertainment & Performers", type: "expense", icon_id: "9" },
      { name: "Audio/Visual Equipment Hire", type: "expense", icon_id: "49" },
      { name: "Printing & Signage", type: "expense", icon_id: "68" },
      { name: "Shipping / Courier Services", type: "expense", icon_id: "70" },
      { name: "Materials & Props", type: "expense", icon_id: "64" },
      { name: "Uniforms / Event Apparel", type: "expense", icon_id: "40" },
      { name: "Licences & Permits", type: "expense", icon_id: "33" },
      { name: "Insurance (Event or Travel)", type: "expense", icon_id: "89" },
      { name: "Marketing & Promotion", type: "expense", icon_id: "32" },
      { name: "Bank Fees", type: "expense", icon_id: "36" },
      { name: "Gifts & Giveaways", type: "expense", icon_id: "56" },
      { name: "Contingency Expenses", type: "expense", icon_id: "93" },
      { name: "Other Travel/ Event Costs", type: "expense", icon_id: "84" }, //two categories

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Education & Training",
    icon: 8,
    // color: '#DDFFDF',
    color: "8",
    description: "Track learning and development costs.",
    default_categories: [
      // ---- incomes ----
      { name: "Scholarships / Grants", type: "income", icon_id: "12" },
      { name: "Training Program Fees Received", type: "income", icon_id: "29" },
      { name: "Course Reimbursements", type: "income", icon_id: "23" },
      { name: "Event / Seminar Ticket Sales", type: "income", icon_id: "26" },
      { name: "Government Education Funding", type: "income", icon_id: "13" },
      {
        name: "Donations for Education Programs",
        type: "income",
        icon_id: "8",
      },
      { name: "Other Education Income", type: "income", icon_id: "2" },

      // ---- expenses ----
      { name: "Tuition Fees", type: "expense", icon_id: "44" },
      {
        name: "Registration / Enrollment Fees",
        type: "expense",
        icon_id: "44",
      },
      { name: "Examination Fees", type: "expense", icon_id: "44" },
      { name: "Textbooks", type: "expense", icon_id: "6" },
      { name: "eBooks & Digital Resources", type: "expense", icon_id: "6" },
      { name: "Stationery & Printing", type: "expense", icon_id: "68" },
      {
        name: "Software Licences (Learning Tools)",
        type: "expense",
        icon_id: "83",
      },
      { name: "Seminar / Conference Fees", type: "expense", icon_id: "44" },
      { name: "Workshop & Short Course Costs", type: "expense", icon_id: "44" },
      {
        name: "Guest Speaker / Instructor Fees",
        type: "expense",
        icon_id: "22",
      },
      {
        name: "Transport (to/from classes or events)",
        type: "expense",
        icon_id: "77",
      },
      {
        name: "Accommodation (study-related trips)",
        type: "expense",
        icon_id: "89",
      },
      {
        name: "Meals & Refreshments (training days)",
        type: "expense",
        icon_id: "46",
      },
      {
        name: "Memberships (Professional/Educational Bodies)",
        type: "expense",
        icon_id: "66",
      },
      {
        name: "Certification / Accreditation Fees",
        type: "expense",
        icon_id: "6",
      },
      { name: "Bank Fees", type: "expense", icon_id: "33" },
      { name: "Insurance (Education-related)", type: "expense", icon_id: "60" },
      {
        name: "Study Equipment (e.g., laptop, headset)",
        type: "expense",
        icon_id: "11",
      },
      {
        name: "Internet Costs (for online study)",
        type: "expense",
        icon_id: "61",
      },
      {
        name: "Other Education/Training Expenses",
        type: "expense",
        icon_id: "44",
      },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Family & Shared Living",
    icon: 9,
    // color: '#D7FFF8',
    color: "9",
    description: "Manage expenses in a shared household or family environment.",
    default_categories: [
      // ---- incomes ----
      { name: "Household Member Contributions", type: "income", icon_id: "38" },
      { name: "Bill Reimbursements", type: "income", icon_id: "23" },
      { name: "Shared Grocery Contributions", type: "income", icon_id: "52" },
      { name: "Rent from Roommates", type: "income", icon_id: "2" },
      { name: "Gifts & Support Payments", type: "income", icon_id: "56" },
      { name: "Refunds & Rebates (Household)", type: "income", icon_id: "6" },
      { name: "Other Shared Living Income", type: "income", icon_id: "2" },

      // ---- expenses ----
      { name: "Rent / Mortgage Payments", type: "expense", icon_id: "67" },
      { name: "Electricity", type: "expense", icon_id: "14" },
      { name: "Water", type: "expense", icon_id: "47" },
      { name: "Gas", type: "expense", icon_id: "54" },
      { name: "Internet / Phone", type: "expense", icon_id: "61" },
      { name: "Council Rates", type: "expense", icon_id: "18" },
      { name: "Groceries", type: "expense", icon_id: "52" },
      { name: "Household Cleaning Supplies", type: "expense", icon_id: "38" },
      { name: "Toiletries & Personal Care", type: "expense", icon_id: "87" },
      { name: "Fuel", type: "expense", icon_id: "22" },
      { name: "Public Transport", type: "expense", icon_id: "23" },
      { name: "Rideshare / Taxi", type: "expense", icon_id: "77" }, // skipping 24 for system items
      { name: "Parking & Tolls", type: "expense", icon_id: "26" },
      { name: "Dining Out (Family/Group)", type: "expense", icon_id: "46" },
      { name: "Takeaway / Delivery", type: "expense", icon_id: "78" },
      { name: "Streaming Subscriptions", type: "expense", icon_id: "83" },
      { name: "Childcare", type: "expense", icon_id: "37" },
      { name: "School Fees & Supplies", type: "expense", icon_id: "44" },
      { name: "Kids’ Activities", type: "expense", icon_id: "37" },
      { name: "Pet Food", type: "expense", icon_id: "73" },
      { name: "Vet Bills", type: "expense", icon_id: "73" },
      { name: "Pet Accessories", type: "expense", icon_id: "73" },
      {
        name: "Repairs & Maintenance (Household)",
        type: "expense",
        icon_id: "59",
      },
      { name: "Furniture & Appliances", type: "expense", icon_id: "55" },
      { name: "Gifts & Celebrations", type: "expense", icon_id: "56" },
      { name: "Other Household Expenses", type: "expense", icon_id: "59" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Construction",
    icon: 10,
    // color: '#CCE6FF',
    color: "10",
    description:
      "Track materials, labor, and logistics for construction sites.",
    default_categories: [
      // ---- incomes ----
      { name: "Contract Payments", type: "income", icon_id: "3" },
      { name: "Progress / Milestone Payments", type: "income", icon_id: "3" },
      {
        name: "Variation Orders / Change Requests",
        type: "income",
        icon_id: "3",
      },
      { name: "Equipment Hire Income", type: "income", icon_id: "49" },
      { name: "Sale of Materials / Scrap", type: "income", icon_id: "64" },
      { name: "Government Grants / Rebates", type: "income", icon_id: "6" },
      {
        name: "Insurance Payouts (Construction)",
        type: "income",
        icon_id: "14",
      },
      { name: "Other Construction Income", type: "income", icon_id: "19" },

      // ---- expenses ----
      { name: "Building Materials", type: "expense", icon_id: "64" },
      {
        name: "Concrete / Cement / Aggregates",
        type: "expense",
        icon_id: "64",
      },
      { name: "Timber & Carpentry Supplies", type: "expense", icon_id: "64" },
      { name: "Steel & Metal Products", type: "expense", icon_id: "64" },
      { name: "Plumbing Supplies", type: "expense", icon_id: "64" },
      { name: "Electrical Supplies", type: "expense", icon_id: "64" },
      { name: "Paint & Finishes", type: "expense", icon_id: "59" },
      { name: "Tools & Small Equipment", type: "expense", icon_id: "20" },
      { name: "Employee Wages (Site Staff)", type: "expense", icon_id: "25" },
      {
        name: "Contractor / Subcontractor Payments",
        type: "expense",
        icon_id: "43",
      },
      { name: "Site Supervision Costs", type: "expense", icon_id: "25" },
      { name: "Training & Certification Fees", type: "expense", icon_id: "31" },
      { name: "Equipment Hire / Lease", type: "expense", icon_id: "0" },
      { name: "Equipment Purchase", type: "expense", icon_id: "45" },
      { name: "Fuel for Machinery", type: "expense", icon_id: "54" },
      {
        name: "Repairs & Maintenance (Equipment)",
        type: "expense",
        icon_id: "79",
      },
      { name: "Delivery Charges", type: "expense", icon_id: "70" },
      { name: "Freight & Courier Services", type: "expense", icon_id: "70" },
      { name: "Vehicle Costs (Site Use)", type: "expense", icon_id: "91" },
      { name: "Safety Gear / PPE", type: "expense", icon_id: "82" },
      { name: "Site Safety Inspections", type: "expense", icon_id: "82" },
      { name: "Permits & Licences", type: "expense", icon_id: "35" },
      { name: "Insurance (Site / Project)", type: "expense", icon_id: "36" },
      { name: "Site Office Utilities", type: "expense", icon_id: "90" },
      { name: "Printing & Documentation", type: "expense", icon_id: "68" },
      { name: "Accounting / Bookkeeping Fees", type: "expense", icon_id: "39" },
      { name: "Legal Fees", type: "expense", icon_id: "62" },
      { name: "Waste Disposal / Skip Bins", type: "expense", icon_id: "92" },
      { name: "Temporary Fencing / Security", type: "expense", icon_id: "81" },
      { name: "Other Construction Expenses", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  {
    name: "Club or Social group",
    icon: 11,
    // color: '#F0F0F0',
    color: "11",
    description:
      "Track contributions and expenses for clubs and social gatherings.",
    default_categories: [
      // ---- incomes ----
      { name: "Membership Fees", type: "income", icon_id: "29" },
      { name: "Event Ticket Sales", type: "income", icon_id: "26" },
      { name: "Sponsorship Income", type: "income", icon_id: "3" },
      { name: "Fundraising Income", type: "income", icon_id: "8" },
      { name: "Donations", type: "income", icon_id: "36" },
      { name: "Charitable Contributions", type: "income", icon_id: "8" },
      { name: "Merchandise Sales", type: "income", icon_id: "26" },
      { name: "Grants / Funding", type: "income", icon_id: "10" },
      { name: "Facility Hire Income", type: "income", icon_id: "22" },
      { name: "Other Club Income", type: "income", icon_id: "19" },

      // ---- expenses ----
      { name: "Venue Hire", type: "expense", icon_id: "13" },
      { name: "Catering & Refreshments", type: "expense", icon_id: "46" },
      { name: "Entertainment & Performers", type: "expense", icon_id: "48" },
      { name: "Decorations & Event Setup", type: "expense", icon_id: "16" },
      { name: "Equipment Hire (Events)", type: "expense", icon_id: "49" },
      { name: "Training & Workshops", type: "expense", icon_id: "31" },
      { name: "Awards & Recognition", type: "expense", icon_id: "6" },
      { name: "Uniforms / Apparel", type: "expense", icon_id: "40" },
      { name: "Member Gifts", type: "expense", icon_id: "12" },
      { name: "Office Supplies & Printing", type: "expense", icon_id: "68" },
      { name: "Postage & Courier", type: "expense", icon_id: "70" },
      {
        name: "Cleaning & Maintenance Supplies",
        type: "expense",
        icon_id: "38",
      }, // 24 reserved for system
      { name: "Storage Rental", type: "expense", icon_id: "86" },
      { name: "Transport for Events", type: "expense", icon_id: "77" },
      { name: "Fuel & Vehicle Hire", type: "expense", icon_id: "28" },
      { name: "Accommodation (Club Trips)", type: "expense", icon_id: "89" },
      {
        name: "Insurance (Public Liability, Event)",
        type: "expense",
        icon_id: "60",
      },
      { name: "Licences & Permits", type: "expense", icon_id: "31" },
      { name: "Accounting / Bookkeeping Fees", type: "expense", icon_id: "32" },
      { name: "Bank Fees", type: "expense", icon_id: "33" },
      { name: "Marketing & Promotion", type: "expense", icon_id: "32" },
      { name: "Technology & Software", type: "expense", icon_id: "83" },
      { name: "Other Club Expenses", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
  // {
  //     name: 'Other',
  //     icon: 12,
  //     // color: '#E6DBCC',
  //     color: "12",
  //     description: 'Custom purpose zones not covered by other categories.',
  //     default_categories: [
  //         { name: 'Balance Correction Expense', type: 'expense', icon_id: '24' },
  //         { name: 'Balance Correction Income', type: 'income', icon_id: "12" },
  //         { name: 'Fund Transfer Expense', type: 'expense', icon_id: "24" },
  //         { name: 'Fund Transfer Income', type: 'income', icon_id: "12" },
  //         { name: 'Payment Expense', type: 'expense', icon_id: "24" },
  //         { name: 'Payment Income', type: 'income', icon_id: "12" },
  //     ],
  // },
  {
    name: "Petty cash",
    icon: 13,
    // color: '#E6DBCC',
    color: "13",
    description: "Manage petty cash expenses.",
    default_categories: [
      // ---- incomes ----
      { name: "Cash Top-Up / Float Refill", type: "income", icon_id: "93" },
      { name: "Reimbursement from Staff", type: "income", icon_id: "85" },
      { name: "Refunds (Petty Cash Purchases)", type: "income", icon_id: "20" },
      { name: "Sale of Scrap / Small Assets", type: "income", icon_id: "45" },
      { name: "Other Petty Cash Income", type: "income", icon_id: "20" },

      // ---- expenses ----
      { name: "Stationery", type: "expense", icon_id: "13" },
      { name: "Printing & Photocopying", type: "expense", icon_id: "68" },
      { name: "Postage & Courier", type: "expense", icon_id: "15" },
      { name: "Kitchen Supplies", type: "expense", icon_id: "46" },
      { name: "Light Bulbs & Fixtures", type: "expense", icon_id: "47" },
      {
        name: "Tools & Small Equipment Repairs",
        type: "expense",
        icon_id: "27",
      },
      { name: "Cleaning Supplies", type: "expense", icon_id: "38" },
      { name: "Taxi / Rideshare Fares", type: "expense", icon_id: "77" },
      { name: "Public Transport Fares", type: "expense", icon_id: "77" },
      { name: "Parking Fees", type: "expense", icon_id: "22" },
      { name: "Staff Lunch / Meeting Snacks", type: "expense", icon_id: "85" },
      { name: "Beverages", type: "expense", icon_id: "52" },
      { name: "Flyers / Posters Printing", type: "expense", icon_id: "68" },
      { name: "Small Promotional Items", type: "expense", icon_id: "32" },
      { name: "Emergency Purchases", type: "expense", icon_id: "42" },
      {
        name: "Small Gifts / Tokens of Appreciation",
        type: "expense",
        icon_id: "12",
      },
      { name: "Other Petty Cash Expenses", type: "expense", icon_id: "93" },

      // ---- system items (as specified) ----
      { name: "Miscellaneous", type: "expense", icon_id: "11" },
      { name: "Balance Correction Expense", type: "expense", icon_id: "24" },
      { name: "Balance Correction Income", type: "income", icon_id: "12" },
      { name: "Fund Transfer Expense", type: "expense", icon_id: "24" },
      { name: "Fund Transfer Income", type: "income", icon_id: "12" },
      { name: "Payment Expense", type: "expense", icon_id: "24" },
    ],
  },
];
